"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-c=d%g!y%qnrq5c*eg3=i++m*&jkslbxhka)klzj&$bp(=+jcl+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
from decouple import config

# Application definition
import os

IS_CI = "true"

INSTALLED_APPS = [
    # "admin_interface",
    #     "colorfield",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "uploader_and_downloader",
    "contenu.apps.ContentConfig",
    "rest_framework",
    "django_celery_beat",
    "processing.apps.ProcessingConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",  # "backends" pas "bacvkends"
        "NAME": config("DATABASE_NAME"),
        "USER": config("DATABASE_USERNAME"),
        "PASSWORD": config("DATABASE_PASSWORD"),
        "HOST": config("DATABASE_HOSTNAME"),
        "PORT": config("DATABASE_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

import os

DROPBOX_APP_KEY = config("DROPBOX_APP_KEY")
DROPBOX_APP_SECRET = config("DROPBOX_APP_SECRET")
DROPBOX_REFRESH_TOKEN = config("DROPBOX_REFRESH_TOKEN")

DROPBOX_ACCESS_TOKEN_CACHE_KEY = os.getenv(
    "DROPBOX_ACCESS_TOKEN_CACHE_KEY", "dropbox:access_token"
)
DROPBOX_TOKEN_EXPIRY_CACHE_KEY = os.getenv(
    "DROPBOX_TOKEN_EXPIRY_CACHE_KEY", "dropbox:access_token_expiry"
)

# Configuration Redis POUR TOUT (production)
CACHES = {
    # DÉFAUT : Redis pour toute l'application
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{config('REDIS_HOST')}:{config('REDIS_PORT')}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "PASSWORD": config('REDIS_PASSWORD'),
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 100,
                "retry_on_timeout": True,
            },
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
        "KEY_PREFIX": "olf_app",
        "TIMEOUT": 3600,
    },
    # OTP : AUSSI dans Redis (mais base séparée)
    "otp": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{config('REDIS_HOST')}:{config('REDIS_PORT')}/3",  # Base 3 pour OTP
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 3,
            "SOCKET_TIMEOUT": 3,
        },
        "KEY_PREFIX": "otp",
        "TIMEOUT": 300,  # 5 minutes - OTP expire rapidement
    },
    "notifications": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{config('REDIS_HOST')}:{config('REDIS_PORT')}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 1,  # Plus agressif
            "SOCKET_TIMEOUT": 1,
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
        "KEY_PREFIX": "notifications",
        "TIMEOUT": 60,
    },
    # CACHE COMPTEURS ENCORE PLUS RAPIDE
    "counters": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{config('REDIS_HOST')}:{config('REDIS_PORT')}/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 0.5,  # Très rapide
            "SOCKET_TIMEOUT": 0.5,
        },
        "KEY_PREFIX": "counters",
        "TIMEOUT": 30,
    },
}

# Redis comme broker pour Celery
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/1"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "refresh-dropbox-token": {
        "task": "uploader_and_downloader.tasks.refresh_dropbox_token_task",
        "schedule": crontab(minute=0, hour="*/2"),  # 2H
    },
    "reindex-svu-indicators-every-15-min": {
        "task": "processing.tasks.indexing.reindex_indicators_task",
        "schedule": crontab(minute="*/1"),
    },
}

worker_prefetch_multiplier = 1
worker_max_tasks_per_child = 20
task_acks_late = True
task_reject_on_worker_lost = True

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Gestion des tâches asynchrones
REDIS_HOST = config("REDIS_HOST", default="redis")
REDIS_PORT = config("REDIS_PORT", cast=int, default=6379)

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/1"

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_POOL_LIMIT = None
CELERY_BROKER_HEARTBEAT = 30
CELERY_BROKER_CONNECTION_TIMEOUT = 30

# Pour éviter les tâches qui restent coincées
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Concurrency et santé worker
CELERY_WORKER_CONCURRENCY = 4
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100

# Formats
CELERY_RESULT_SERIALIZER = "json"

# Timezone
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TIMEZONE = "UTC"

# Configuration des workers
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100

# Configuration Beat
CELERY_BEAT_SCHEDULER = "celery.beat:PersistentScheduler"
CELERY_BEAT_MAX_LOOP_INTERVAL = 300  # 5 minutes

# CELERY_IMPORTS = [
#     "uploader_and_downloader.tasks"
# ]

# Configuration des tâches
# CELERY_TASK_ALWAYS_EAGER = True  # Désactiver pour production
# CELERY_TASK_EAGER_PROPAGATES = True

CELERY_IMPORTS = [
    "uploader_and_downloader.tasks",
    "contenu.tasks.emails",
    "contenu.tasks.etl",
    "contenu.tasks.logs",
    "contenu.tasks.maintenance",
    "contenu.tasks.upload",
]

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent



if IS_CI:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "simple": {
                "format": "[{levelname}] {name} | {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "simple",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "loggers": {
            "django": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
            "celery": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }

else:
    # 🔽 TA CONFIG LOGGING ACTUELLE (FILES)
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": (
                    "[{asctime}] {levelname} "
                    "{name} ({module}:{lineno}) "
                    "pid={process:d} tid={thread:d} "
                    "{message}"
                ),
                "style": "{",
            },
            "simple": {
                "format": "[{levelname}] {name} | {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "level": "INFO",
                "class": "logging.StreamHandler",
                "formatter": "simple",
            },
            "django_file": {
                "level": "INFO",
                "class": "logging.FileHandler",
                "filename": BASE_DIR / "logs/django.log",
                "formatter": "verbose",
            },
            "celery_file": {
                "level": "INFO",
                "class": "logging.FileHandler",
                "filename": BASE_DIR / "logs/celery.log",
                "formatter": "verbose",
            },
            "contenu_file": {
                "level": "INFO",
                "class": "logging.FileHandler",
                "filename": BASE_DIR / "logs/contenu.log",
                "formatter": "verbose",
            },
            "errors_file": {
                "level": "ERROR",
                "class": "logging.FileHandler",
                "filename": BASE_DIR / "logs/errors.log",
                "formatter": "verbose",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["console", "django_file"],
                "level": "INFO",
                "propagate": True,
            },
            "celery": {
                "handlers": ["console", "celery_file"],
                "level": "INFO",
                "propagate": False,
            },
            "celery.task": {
                "handlers": ["console", "celery_file"],
                "level": "INFO",
                "propagate": False,
            },
            "contenu": {
                "handlers": ["console", "contenu_file"],
                "level": "INFO",
                "propagate": False,
            },
            "uploader_and_downloader": {
                "handlers": ["console", "contenu_file"],
                "level": "INFO",
                "propagate": False,
            },
            "": {
                "handlers": ["errors_file"],
                "level": "ERROR",
            },
        },
    }



DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
