# Generated by Django 5.2.9 on 2025-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtractionDB",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("document_id", models.CharField(max_length=36, unique=True)),
                ("status", models.CharField(max_length=20)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "extractions",
                "indexes": [
                    models.Index(
                        fields=["document_id"], name="extractions_documen_d0ba57_idx"
                    ),
                    models.Index(
                        fields=["status"], name="extractions_status_ef9bb7_idx"
                    ),
                ],
            },
        ),
    ]
