# Generated by Django 5.2.9 on 2025-12-31 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Category des indicateurs",
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "indicator_code",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("label", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, null=True)),
                ("value_type", models.CharField(blank=True, max_length=50, null=True)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("validation_rules", models.JSONField(blank=True, null=True)),
                ("source", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indicators",
                        to="processing.indicatorcategory",
                    ),
                ),
            ],
            options={
                "db_table": "indicateurs",
                "indexes": [
                    models.Index(
                        fields=["indicator_code"], name="indicateurs_indicat_2df939_idx"
                    ),
                    models.Index(
                        fields=["indicator_id"], name="indicateurs_indicat_736eb0_idx"
                    ),
                ],
            },
        ),
    ]
