# Generated by Django 6.0 on 2025-12-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentDB",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("tenant_id", models.CharField(max_length=36)),
                ("submitted_by", models.CharField(max_length=36)),
                ("filename", models.CharField(max_length=255)),
                ("size", models.BigIntegerField()),
                ("source_type", models.CharField(max_length=50)),
                ("storage_uri", models.URLField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=128, null=True)),
                ("status", models.CharField(default="DRAFT", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "documents",
            },
        ),
    ]
