# Generated by Django 6.0 on 2025-12-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentdb",
            options={"verbose_name_plural": "Documents"},
        ),
        migrations.RemoveField(
            model_name="documentdb",
            name="tenant_id",
        ),
    ]
