# Generated by Django 5.2.9 on 2025-12-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenu", "0002_alter_documentdb_options_remove_documentdb_tenant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentdb",
            name="document_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
